### ISSUE TITLE
对各个项目进行细化，制作设计文档

### ISSUE THREAD

**Issue by dbydd** [Geschichtlicher-Kampf-Kraft-GKK/GKK-Client#11]
比如机械部分，应当写明机器处理的配方，配件，运作流程，内部部件（几个槽位，几个储罐），是否需要tesr，需要哪些blockstate等

**Comment by sun-wilhelm** [comment]
机械制造mod尚未列在目前的或者下一步的任务计划列表中 只是执行初步的设定。
当机械制造已经处于下一步之行的方案中时 会补充设定。
